# ROS parameters
topics:
  image_left_topic: "/cam_0/image_raw"
  image_right_topic: "/cam_1/image_raw"
  pointcloud_topic: "/cortex/ouster/points"

# Dense Stereo parameters
vfov: 100
ndisp: 80
wsize: 7
min_dist: 1
max_dist: 7.5

# ICP parameters 
max_correspondence_distance: 0.5
max_iterations: 20

# Init transformation of the lidar in left camera frame
T_lidar_cam0: [0.00162123, -0.0082983, -0.999964, -0.143336, 
  0.99966, 0.0260173, 0.00140483, 0.0823592, 
  0.0260047, -0.999627, 0.00833766, -0.349024, 
  0.0, 0.0, 0.0, 1.0]